app = "rsslay"
primary_region = "yyz"
kill_signal = "SIGINT"
kill_timeout = 5

[experimental]
  enable_consul = true

[metrics]
  port = 8080
  path = "/metrics"

[env]
  DB_DIR = "/var/lib/litefs/db"
  DEFAULT_PROFILE_PICTURE_URL = "https://i.imgur.com/MaceU96.png"
  DEFAULT_WAIT_TIME_BETWEEN_BATCHES = "60000"
  DEFAULT_WAIT_TIME_FOR_RELAY_RESPONSE = "1000"
  DELETE_FAILING_FEEDS = "false"
  ENABLE_AUTO_NIP05_REGISTRATION = "true"
  INFO_CONTACT = "mailto:raul@piraces.dev"
  INFO_RELAY_NAME = "rsslay public instance"
  LOG_LEVEL = "INFO"
  MAIN_DOMAIN_NAME = "rsslay.nostr.moe"
  MAX_CONTENT_LENGTH = "5000"
  MAX_EVENTS_TO_REPLAY = "10"
  MAX_SUBROUTINES = "20"
  NITTER_INSTANCES = "birdsite.xanny.family,notabird.site,nitter.moomoo.me,nitter.fly.dev"
  OWNER_PUBLIC_KEY = "4ac24d2ee822a34a9881eff526bf71f39704419837e4c14b34642d82e111ed39"
  PORT = "8080"
  RELAYS_TO_PUBLISH_TO = ""
  REPLAY_TO_RELAYS = "false"
  VERSION = "0.5.4"

[[mounts]]
  source = "rsslay_data_machines"
  destination = "/var/lib/litefs"
  processes = ["app"]

[[services]]
  protocol = "tcp"
  internal_port = 8080

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 250
    soft_limit = 100

  [[services.http_checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    restart_limit = 0
    method = "get"
    path = "/healthz"
    protocol = "http"
